# -*- coding: utf-8 -*-
"""AI-Code-Reviewer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVOpEAPx0LDo_mmk_uDWm8w5nLt8RLUn
"""

import google.generativeai as genai
import gradio as gr

# Configure Gemini API
genai.configure(api_key="YOUR_GEMINI_API_KEY")

model = genai.GenerativeModel("gemini-2.5-flash")

def review_code(code, input_programming_language, output_programming_language):

    prompt = f"""
Review the following {input_programming_language} code.

Also convert it into {output_programming_language}.

Provide:

1. Summary
2. Bugs
3. Performance Improvements
4. Code Style Suggestions
5. Security Issues
6. Improved Code
7. Rating out of 10

Code:
{code}
"""

    response = model.generate_content(prompt)

    return response.text


demo = gr.Interface(
    fn=review_code,
    inputs=[
        gr.Textbox(lines=15, label="Enter Code"),

        gr.Dropdown(
            ["Python", "Java", "HTML", "CSS"],
            label="Input Programming Language"
        ),

        gr.Dropdown(
            ["Python", "Java", "HTML", "CSS"],
            label="Output Programming Language"
        ),
    ],

    outputs=gr.Markdown(),

    title=" AI Code Review with Gemini",

    description="Upload or paste your code to get AI-powered review, improvements, bug detection, and code conversion."
)

demo.launch(debug=True)